providers:
  amazon:
    name: Amazon
    icon: amazon.svg
    models:
      nova:
        id: us.amazon.nova-pro-v1:0
        name: Nova Pro
        capabilities:
          - text
          - image
      titan:
        id: amazon.titan-text-express-v1
        name: Titan Text G1 - Express
        capabilities:
          - text
  anthropic:
    name: Anthropic
    icon: anthropic.svg
    models:
      claude-3-sonnet:
        id: anthropic.claude-3-sonnet-20240229-v1:0
        name: Claude 3 Sonnet
        capabilities:
          - text
          - image
      claude-3.5-sonnet-v2:
        id: anthropic.claude-3-5-sonnet-20241022-v2:0
        name: Claude 3.5 Sonnet v2
        capabilities:
          - text
          - image
      claude-3.5-haiku:
        id: anthropic.claude-3-5-haiku-20241022-v1:0
        name: Claude 3.5 Haiku
        capabilities:
          - text
  meta:
    name: Meta
    icon: meta.svg
    models:
      llama-3.3-8b-instruct:
        id: us.meta.llama3-3-8b-instruct-v1:0
        name: Llama 3.3 8B Instruct
        capabilities:
          - text
